import type { FieldTestInbox } from './fieldQuestEngine';

/** Explicit public test gates: these cards are NOT recorded participation events. */
export const FIELD_TEST_INBOX: FieldTestInbox = {
  schema: 'static.field-test-inbox/v0',
  entries: [
    {
      schema: 'static.field-test-entry/v0',
      id: 'skymirror-002-first-light',
      source_project: 'SKYMIRROR-002',
      source_repository: 'the-static-collective/reLATTE',
      source_commit: '540da48104a8a76a87f2acefd60df00ffa76237c',
      source_path: 'experiments/SKYMIRROR-002/README.md',
      source_gate: 'actual indoor phone-screen → household mirror → second-phone camera capture',
      title: 'The First Light Crossing',
      question: 'Can two phones transmit and recover HI using only reflected screen light, after static web pages have loaded?',
      scale: 'QUEST',
      required_materials: ['Two phones', 'One household mirror', 'Safe indoor test space'],
      procedure: ['Read the SKYMIRROR-002 physical test safety instructions',
        'Open the HTTPS lab on both devices and load code before disconnecting networks',
        'Start camera receiver, observe reflected screen, transmit HI, and capture full run'],
      safety_boundaries: ['Use ordinary phone screens indoors only',
        'No lasers, no sky-directed beams, and no unsolicited recording of people'],
      return_evidence: ['Original receiver brightness JSON', 'Observed decode or failure',
        'Hardware/browser details and independent repeat attempt'],
      condition: 'READY_FOR_FIELD_TEST',
      condition_ref: null,
      possible_descendant: 'If field evidence survives review, attempt an independent device-to-device repetition.',
      status: 'PHYSICAL_UNVERIFIED',
      provenance_note: 'Protocol and synthetic checks are software results; a real camera link is still unverified.',
    },
    {
      schema: 'static.field-test-entry/v0',
      id: 'skymirror-002-independent-repeat',
      source_project: 'SKYMIRROR-002',
      source_repository: 'the-static-collective/reLATTE',
      source_commit: '540da48104a8a76a87f2acefd60df00ffa76237c',
      source_path: 'experiments/SKYMIRROR-002/README.md',
      source_gate: 'independent optical repeat under a different arrangement',
      title: 'Second Light, Different Eyes',
      question: 'Does a separate device arrangement reproduce the measured result without assuming the first attempt succeeded?',
      scale: 'PARTY_ARC',
      required_materials: ['Different camera or display arrangement', 'A second observer if available'],
      procedure: ['Review the first field measurement with an authorized human',
        'Choose a materially different arrangement', 'Capture raw samples and compare with the original'],
      safety_boundaries: ['Do not turn a failed field attempt into a false success',
        'Keep all light tests indoors, screen-only and voluntary'],
      return_evidence: ['Original second-run brightness JSON', 'Cross-run comparison', 'Human-reviewed divergence'],
      condition: 'NEEDS_PRIOR_WITNESS',
      condition_ref: 'skymirror-002-first-light',
      possible_descendant: 'A stronger channel model or a new calibration quest may become possible.',
      status: 'PHYSICAL_UNVERIFIED',
      provenance_note: 'Conditional proposal only. There is no verified first physical link yet.',
    },
  ],
};
