import { JubileeDataStore } from '../types.js';

export const initialSeedStore: JubileeDataStore = {
  profiles: [
    {
      id: 'user_lu',
      displayName: 'Lu',
      note: 'Lover of wood, gardens, and heavy loads.',
      avatarColor: 'bg-amber-700 text-amber-50',
      createdAt: '2026-07-01T10:00:00.000Z',
    },
    {
      id: 'user_grace',
      displayName: 'Grace',
      note: 'Singer, baker, and community weaver.',
      avatarColor: 'bg-emerald-800 text-emerald-50',
      createdAt: '2026-07-01T10:05:00.000Z',
    },
    {
      id: 'user_michael',
      displayName: 'Michael',
      note: 'Hands-on fixer with tools to spare.',
      avatarColor: 'bg-stone-700 text-stone-50',
      createdAt: '2026-07-01T10:10:00.000Z',
    },
    {
      id: 'user_jen',
      displayName: 'Jen',
      note: 'Nourisher and harvest cook.',
      avatarColor: 'bg-terracotta-700 text-amber-50',
      createdAt: '2026-07-01T10:15:00.000Z',
    },
  ],
  circles: [
    {
      id: 'circle_1',
      name: 'The First Campfire',
      description: 'A small trusted circle offering gifts, opening needs, and remembering shared capacity.',
      inviteCode: 'CAMPFIRE1',
      createdBy: 'user_lu',
      createdAt: '2026-07-01T10:00:00.000Z',
    },
  ],
  circleMembers: [
    { circleId: 'circle_1', userId: 'user_lu', role: 'steward', joinedAt: '2026-07-01T10:00:00.000Z' },
    { circleId: 'circle_1', userId: 'user_grace', role: 'member', joinedAt: '2026-07-01T10:05:00.000Z' },
    { circleId: 'circle_1', userId: 'user_michael', role: 'member', joinedAt: '2026-07-01T10:10:00.000Z' },
    { circleId: 'circle_1', userId: 'user_jen', role: 'member', joinedAt: '2026-07-01T10:15:00.000Z' },
  ],
  circleInvitations: [
    {
      id: 'inv_1',
      circleId: 'circle_1',
      code: 'CAMPFIRE1',
      createdById: 'user_lu',
      note: 'Welcome to The First Campfire circle!',
      maxUses: null,
      usesCount: 4,
      createdAt: '2026-07-01T10:00:00.000Z',
    },
  ],
  offers: [
    {
      id: 'offer_lu_truck',
      circleId: 'circle_1',
      offeredBy: 'user_lu',
      title: 'Pickup Truck & Hauling',
      description: 'Sturdy Ford F-150 with tie-down straps. Happy to haul lumber, compost, or furniture.',
      category: 'transport',
      availability: 'Saturdays & Sunday mornings',
      locationNote: 'North Neighborhood / 15 min radius',
      boundaries: 'Fuel contribution appreciated for trips over 30 miles; no chemical hazards.',
      status: 'available',
      makesPossible: ['Bulk lumber transport', 'Compost delivery for garden beds', 'Moving heavy equipment'],
      addressHash: 'jubilee://offer/truck_f150',
      createdAt: '2026-07-02T09:00:00.000Z',
    },
    {
      id: 'offer_grace_singing',
      circleId: 'circle_1',
      offeredBy: 'user_grace',
      title: 'Songs and Group Singing',
      description: 'Leading acoustic vocal harmonies, campfire folk songs, and teaching simple group canons.',
      category: 'creative',
      availability: 'Evenings and weekends',
      locationNote: 'At the Campfire or outdoor spaces',
      boundaries: 'Need a comfortable seating circle or fire pit.',
      status: 'available',
      makesPossible: ['Community hearth gatherings', 'Seasonal work song circles'],
      addressHash: 'jubilee://offer/singing_circle',
      createdAt: '2026-07-02T10:30:00.000Z',
    },
    {
      id: 'offer_michael_drill',
      circleId: 'circle_1',
      offeredBy: 'user_michael',
      title: 'Cordless Drill & Basic Repair Work',
      description: 'DeWalt 20V drill set, bits, saw, and two capable hands for framing and fixes.',
      category: 'tool',
      availability: 'Weekday afternoons after 4pm & weekends',
      locationNote: 'Mobile',
      boundaries: 'Safety glasses required; happy to teach beginners.',
      status: 'available',
      makesPossible: ['Greenhouse timber framing', 'Raised bed carpentry', 'Door & fence repairs'],
      addressHash: 'jubilee://offer/dewalt_drill',
      createdAt: '2026-07-03T11:00:00.000Z',
    },
    {
      id: 'offer_jen_soup',
      circleId: 'circle_1',
      offeredBy: 'user_jen',
      title: 'Hot Soup for Shared Workdays',
      description: 'Hearty lentil or roasted vegetable soup made from local produce with fresh bread.',
      category: 'food',
      availability: 'Needs 2 days notice for prep',
      locationNote: 'Delivered in thermal pots',
      boundaries: 'Serves up to 12 neighbors per batch.',
      status: 'available',
      makesPossible: ['Nourishing communal work parties', 'Harvest celebrations'],
      addressHash: 'jubilee://offer/lentil_soup',
      createdAt: '2026-07-03T14:20:00.000Z',
    },
  ],
  projects: [
    {
      id: 'project_greenhouse',
      circleId: 'circle_1',
      openedBy: 'user_lu',
      title: 'Repair the Greenhouse',
      story: 'The greenhouse frame is still standing, but several panels and braces need repair before the next growing season. Fixing this will allow us to start spring seedlings together.',
      locationNote: 'Lu’s Back Parcel / Community Garden',
      desiredDate: 'This Saturday',
      status: 'forming',
      seedStage: 'Sprout',
      fruit: '200 Heirloom Tomato & Pepper Seedlings',
      futurePossibility: 'If successful, we can start 200 heirloom tomato and pepper seedlings for the entire circle!',
      makesPossible: [
        'Circle Seedling Bank',
        'Spring Neighborhood Plant Swap',
        'Year-round winter greens propagation',
      ],
      addressHash: 'jubilee://seed/project_greenhouse',
      needs: [
        { id: 'need_gh_1', projectId: 'project_greenhouse', title: 'Pickup truck for lumber transport', description: 'Transport 6 long 2x4s and polycarbonate sheets', quantity: 1, unit: 'truck', status: 'open' },
        { id: 'need_gh_2', projectId: 'project_greenhouse', title: 'Cordless drill & bits', description: 'Heavy duty drilling into timber frame', quantity: 1, unit: 'tool', status: 'open' },
        { id: 'need_gh_3', projectId: 'project_greenhouse', title: 'Two people for lifting', description: 'Hold roof panels steady during fastening', quantity: 2, unit: 'neighbors', status: 'open' },
        { id: 'need_gh_4', projectId: 'project_greenhouse', title: 'Warm food for workday', description: 'Nourishment for 6 workers at noon', quantity: 1, unit: 'meal', status: 'open' },
        { id: 'need_gh_5', projectId: 'project_greenhouse', title: 'Someone to document the repair', description: 'Take photographs and note measurements for future maintenance', quantity: 1, unit: 'neighbor', status: 'open' },
      ],
      createdAt: '2026-07-10T08:00:00.000Z',
      completedAt: null,
    },
    {
      id: 'project_oven_fire',
      circleId: 'circle_1',
      openedBy: 'user_grace',
      title: 'Community Oven First Fire',
      story: 'We cured the outdoor cob oven over two weeks. Now we gather for the first official bake fire, sharing sourdough loaves and slow-baked root vegetables.',
      locationNote: 'Common Green Outdoor Hearth',
      desiredDate: 'Last Saturday',
      status: 'completed',
      seedStage: 'Harvest',
      fruit: 'Fired Cob Oven & Sourdough Hearth',
      futurePossibility: 'Regular Saturday communal baking days for neighborhood sourdough and pizzas.',
      makesPossible: [
        'Weekly Sourdough Bake Club',
        'Neighborhood Pizza Nights',
        'Harvest Festival Roasting',
      ],
      addressHash: 'jubilee://seed/project_oven_fire',
      needs: [
        { id: 'need_ov_1', projectId: 'project_oven_fire', title: 'Hardwood firewood', description: 'Dry oak or maple logs', quantity: 2, unit: 'bundles', status: 'met' },
        { id: 'need_ov_2', projectId: 'project_oven_fire', title: 'Sourdough dough prep', description: 'High hydration dough loaves ready for firing', quantity: 6, unit: 'loaves', status: 'met' },
      ],
      createdAt: '2026-07-04T12:00:00.000Z',
      completedAt: '2026-07-05T18:00:00.000Z',
    },
  ],
  pledges: [
    {
      id: 'pledge_oven_1',
      projectId: 'project_oven_fire',
      needId: 'need_ov_1',
      pledgedBy: 'user_michael',
      offerId: 'offer_michael_drill',
      description: 'Brought 2 bundles of seasoned maple firewood from my shed.',
      quantity: 2,
      unit: 'bundles',
      status: 'confirmed',
      createdAt: '2026-07-04T14:00:00.000Z',
      acceptedAt: '2026-07-04T15:00:00.000Z',
      reportedCompleteAt: '2026-07-05T16:00:00.000Z',
      confirmedAt: '2026-07-05T18:00:00.000Z',
    },
    {
      id: 'pledge_oven_2',
      projectId: 'project_oven_fire',
      needId: 'need_ov_2',
      pledgedBy: 'user_jen',
      offerId: 'offer_jen_soup',
      description: 'Prepared and brought sourdough loaves & hot lentil stew.',
      quantity: 6,
      unit: 'loaves',
      status: 'confirmed',
      createdAt: '2026-07-04T14:30:00.000Z',
      acceptedAt: '2026-07-04T15:05:00.000Z',
      reportedCompleteAt: '2026-07-05T16:30:00.000Z',
      confirmedAt: '2026-07-05T18:00:00.000Z',
    },
  ],
  receipts: [
    {
      id: 'receipt_oven_fire',
      circleId: 'circle_1',
      projectId: 'project_oven_fire',
      createdBy: 'user_grace',
      summary: 'Community Oven First Fire',
      outcome: 'The oven was fired successfully. Bread was baked for twelve people. Michael provided seasoned hardwood, and Jen prepared sourdough loaves and lentil stew. The hearth held heat for 4 hours.',
      fruit: 'Fired Cob Oven & Sourdough Hearth',
      makesPossible: [
        'Weekly Sourdough Bake Club',
        'Neighborhood Pizza Nights',
        'Harvest Festival Roasting',
      ],
      addressHash: 'jubilee://receipt/receipt_oven_fire',
      createdAt: '2026-07-05T18:05:00.000Z',
    },
  ],
  capacities: [
    {
      id: 'capacity_community_baking',
      circleId: 'circle_1',
      title: 'Community Baking Day',
      description: 'The circle can now host small community baking days and fire sourdough loaves for shared dinners.',
      sourceReceiptId: 'receipt_oven_fire',
      makesPossible: [
        'Weekly Sourdough Bake Club',
        'Pizza Night for 30 Neighbors',
        'Community Bread Exchange',
      ],
      addressHash: 'jubilee://capacity/community_baking',
      createdAt: '2026-07-05T18:05:00.000Z',
    },
  ],
  domainEvents: [
    {
      id: 'evt_1',
      circleId: 'circle_1',
      aggregateType: 'circle',
      aggregateId: 'circle_1',
      eventType: 'circle.created',
      actorId: 'user_lu',
      payload: { name: 'The First Campfire' },
      createdAt: '2026-07-01T10:00:00.000Z',
    },
    {
      id: 'evt_2',
      circleId: 'circle_1',
      aggregateType: 'offer',
      aggregateId: 'offer_lu_truck',
      eventType: 'offer.created',
      actorId: 'user_lu',
      payload: { title: 'Pickup Truck & Hauling' },
      createdAt: '2026-07-02T09:00:00.000Z',
    },
    {
      id: 'evt_3',
      circleId: 'circle_1',
      aggregateType: 'offer',
      aggregateId: 'offer_grace_singing',
      eventType: 'offer.created',
      actorId: 'user_grace',
      payload: { title: 'Songs and Group Singing' },
      createdAt: '2026-07-02T10:30:00.000Z',
    },
    {
      id: 'evt_4',
      circleId: 'circle_1',
      aggregateType: 'offer',
      aggregateId: 'offer_michael_drill',
      eventType: 'offer.created',
      actorId: 'user_michael',
      payload: { title: 'Cordless Drill & Basic Repair Work' },
      createdAt: '2026-07-03T11:00:00.000Z',
    },
    {
      id: 'evt_5',
      circleId: 'circle_1',
      aggregateType: 'offer',
      aggregateId: 'offer_jen_soup',
      eventType: 'offer.created',
      actorId: 'user_jen',
      payload: { title: 'Hot Soup for Shared Workdays' },
      createdAt: '2026-07-03T14:20:00.000Z',
    },
    {
      id: 'evt_6',
      circleId: 'circle_1',
      aggregateType: 'project',
      aggregateId: 'project_oven_fire',
      eventType: 'project.opened',
      actorId: 'user_grace',
      payload: { title: 'Community Oven First Fire' },
      createdAt: '2026-07-04T12:00:00.000Z',
    },
    {
      id: 'evt_7',
      circleId: 'circle_1',
      aggregateType: 'pledge',
      aggregateId: 'pledge_oven_1',
      eventType: 'pledge.confirmed',
      actorId: 'user_grace',
      payload: { pledgedBy: 'user_michael', description: 'Seasoned maple firewood' },
      createdAt: '2026-07-05T18:00:00.000Z',
    },
    {
      id: 'evt_8',
      circleId: 'circle_1',
      aggregateType: 'receipt',
      aggregateId: 'receipt_oven_fire',
      eventType: 'receipt.created',
      actorId: 'user_grace',
      payload: { summary: 'Community Oven First Fire' },
      createdAt: '2026-07-05T18:05:00.000Z',
    },
    {
      id: 'evt_9',
      circleId: 'circle_1',
      aggregateType: 'capacity',
      aggregateId: 'capacity_community_baking',
      eventType: 'capacity.created',
      actorId: 'user_grace',
      payload: { title: 'Community Baking Day' },
      createdAt: '2026-07-05T18:05:00.000Z',
    },
    {
      id: 'evt_10',
      circleId: 'circle_1',
      aggregateType: 'project',
      aggregateId: 'project_greenhouse',
      eventType: 'project.opened',
      actorId: 'user_lu',
      payload: { title: 'Repair the Greenhouse' },
      createdAt: '2026-07-10T08:00:00.000Z',
    },
  ],
};
